# Generated by Django 5.0.4 on 2024-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pgone', models.CharField(max_length=100)),
            ],
        ),
    ]
