# Generated by Django 5.0.4 on 2024-04-06 20:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('objectType', models.CharField(default='TOUR')),
                ('durationNights', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('promo', models.BooleanField(default=False)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[''], size=8)),
                ('title', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(default='Тур')),
                ('iscanbuy', models.BooleanField(default=True)),
                ('price', models.CharField(default=0)),
                ('destination', models.CharField(null=True)),
                ('hasAudioGuide', models.BooleanField(default=False)),
                ('russpassRecomendation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='myModel',
        ),
    ]
